language: cpp

compiler:
  - gcc

# need to install the Boost libraries to the sandbox
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost-program-options-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: mkdir build && cd build && cmake .. && make && ./BoostOptionsExample --help
